[package]
name = "filesync-api"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = { workspace = true, features = ["http1", "json", "query", "tokio"] }
cap-std.workspace = true
futures-util.workspace = true
http.workspace = true
jsonwebtoken.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "signal", "sync", "time", "fs", "io-util"] }
tokio-util = { workspace = true, features = ["io"] }
uuid.workspace = true
