{ config, lib, pkgs, vars, ... }:

let
  cfg = config.repo.ntfy;

  serverPackage = pkgs.callPackage ./server-package.nix { };

  loopback = vars.networking.loopbackIPv4;
  portString = toString cfg.port;
  host = "ntfy.${vars.domain}";

  # ntfy is unauthenticated by owner decision: `auth-default-access` is left at
  # ntfy's read-write default, so every topic is readable and writable by
  # anyone who can reach the host. Reachability is therefore the only control,
  # and this file is the whole of it.
  #
  # Two invariants follow, and both are asserted in networking.nix rather than
  # left to review: the server binds loopback only, and nothing may publish it
  # through the Cloudflare tunnel. Adding a tunnel route would turn every topic
  # into a public read-write endpoint.
  serverConfig = pkgs.writeText "ntfy-server.yml" ''
    # Generated by the NixOS ntfy module. Local edits are overwritten on rebuild.
    base-url: "https://${host}"
    listen-http: "${loopback}:${portString}"
    # Cache messages for a day; ntfy drops anything older.
    cache-duration: "24h"
    # Retention is bounded by the message cache, so the on-disk database cannot
    # grow without limit from a client that keeps polling.
    attachment-cache-dir: "${cfg.stateDir}/attachments"
    attachment-total-size-limit: "500M"
    attachment-file-size-limit: "15M"
    attachment-expiry-duration: "24h"
    # ntfy's own login UI would imply a credential boundary this deployment does
    # not have, so it stays off and the host serves the push API only.
    web-root: ""
    enable-login: false
    enable-signup: false
    # Uncommenting this line would be a different security posture than the one
    # this host is deployed with. Leaving it out keeps ntfy's read-write default
    # explicit rather than accidental.
    # auth-default-access: "deny-all"
  '';
in
{
  options.repo.ntfy = {
    enable = lib.mkEnableOption ''
      Self-hosted ntfy push notification server, reachable on the LAN and the
      NetBird overlay only. Topics are unauthenticated by owner decision, so the
      host must never be published through the Cloudflare tunnel.
    '';

    package = lib.mkOption {
      type = lib.types.package;
      default = serverPackage;
      description = "The ntfy server binary. Built from source; nixpkgs ships no ntfy server.";
    };

    port = lib.mkOption {
      type = lib.types.port;
      default = vars.networking.ports.ntfy or 8099;
      description = "Loopback port the ntfy server listens on. Caddy is the only ingress.";
    };

    stateDir = lib.mkOption {
      type = lib.types.str;
      default = "/var/lib/ntfy";
      description = "Writable ntfy state root holding the message cache and attachments.";
    };

    configFile = lib.mkOption {
      type = lib.types.path;
      default = serverConfig;
      readOnly = true;
      description = "Generated server.yml binding the loopback address.";
    };
  };

  config = lib.mkIf cfg.enable {
    # StateDirectory gives the unit a writable /var/lib/ntfy owned by the ntfy
    # user, which is also the persisted impermanence path.
    systemd.tmpfiles.rules = [
      "d ${cfg.stateDir} 0755 ntfy ntfy -"
    ];
  };
}