[package]
name = "kanidm-canary-bootstrap"
version.workspace = true
edition.workspace = true

[dependencies]
data-encoding.workspace = true
hmac.workspace = true
kanidm_client.workspace = true
kanidm_proto.workspace = true
sha2.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }

[dev-dependencies]
tempfile.workspace = true
