#!/usr/bin/env python3
"""Generate wire types and validation data from Media Manager's OpenAPI contract.
Python/PyYAML are build tooling only; no new application runtime dependency.
"""
import argparse
import json
from pathlib import Path
import sys
import yaml

ROOT = Path(__file__).resolve().parents[2]
APP = ROOT / "custom_apps/rust/apps/media-manager"

def typescript(schema):
    if schema is False:
        return "never"
    if schema is True or not schema:
        return "unknown"
    if schema.get("nullable"):
        return "(" + typescript({key: value for key, value in schema.items() if key != "nullable"}) + ") | null"
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    for key, separator in [("allOf", " & "), ("anyOf", " | "), ("oneOf", " | ")]:
        if key in schema:
            return "(" + separator.join(typescript(item) for item in schema[key]) + ")"
    kind = schema.get("type", "object" if "properties" in schema else None)
    if isinstance(kind, list):
        return " | ".join(typescript(dict(schema, type=item)) for item in kind)
    if kind == "array":
        return "Array<" + typescript(schema.get("items", {})) + ">"
    if kind == "object":
        props = schema.get("properties", {})
        if not props:
            return "Record<string, " + typescript(schema.get("additionalProperties", {})) + ">"
        required = schema.get("required", [])
        return "{ " + " ".join(json.dumps(key) + ("" if key in required else "?") + ": " + typescript(value) + ";" for key, value in props.items()) + " }"
    return {"integer": "number", "number": "number", "string": "string", "boolean": "boolean", "null": "null"}.get(kind, "unknown")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    contract = yaml.safe_load((APP / "openapi.yaml").read_text())
    schemas = contract["components"]["schemas"]
    responses = []
    for path, methods in contract["paths"].items():
        for method, operation in methods.items():
            if method not in ["get", "post", "put", "patch", "delete"]:
                continue
            for status, response in operation.get("responses", {}).items():
                schema = response.get("content", {}).get("application/json", {}).get("schema")
                if schema is None and str(status) == "204":
                    schema = {"type": "null"}
                if schema is not None:
                    responses.append(dict(path=path, method=method.upper(), status=str(status), schema=schema))
    data = json.dumps(dict(components=dict(schemas=schemas), responses=responses), separators=(",", ":"), ensure_ascii=True)
    ts = "// Generated by scripts/helpers/generate-media-api.py; edit openapi.yaml.\n"
    ts += "\n".join("/* prettier-ignore */\nexport type " + name + " = " + typescript(schema) + ";" for name, schema in schemas.items())
    ts += "\n/* prettier-ignore */\nexport const contract: unknown = " + data + ";\n"
    rust = '// Generated by scripts/helpers/generate-media-api.py; edit openapi.yaml.\npub const API_CONTRACT: &str = r###"' + data + '"###;\n'
    outputs = {APP / "frontend/src/api-contract.generated.ts": ts, APP / "tests/support/api_contract_generated.rs": rust}
    stale = []
    for path, text in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(text)
    if stale:
        sys.exit("Stale generated API contracts: " + ", ".join(stale))

if __name__ == "__main__":
    main()
