#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$script_dir/helpers/repo-common.sh"
init_repo_root "SMARTD_CONFIG_REPO_ROOT"
cd_repo_root
ensure_default_nix_config

need jq

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT
discovery_json_file="${tmpdir}/storage-discovery.json"

"$repo_root/scripts/discover-storage-devices.sh" --format json >"$discovery_json_file"

cat <<'EOF'
# Autogenerated by scripts/generate-smartd-config.sh
DEFAULT -a
EOF

while IFS= read -r disk_json; do
  [[ -n "$disk_json" ]] || continue
  device="$(jq -r '.device' <<<"$disk_json")"
  args="$(jq -r '(.smartctlArgs // []) | join(" ")' <<<"$disk_json")"
  if [[ -n "$args" ]]; then
    printf '%s %s\n' "$device" "$args"
  else
    printf '%s\n' "$device"
  fi
done < <(jq -c '.allSmartDisks[]' "$discovery_json_file")
