{ config, lib, pkgs, vars, ... }:

let
  discoveryConfig = pkgs.writeText "storage-device-discovery.json" (builtins.toJSON {
    storageProfile = vars.storageProfile;
    systemDisk = {
      diskId = vars.mainDisk;
      device = "/dev/disk/by-id/${vars.mainDisk}";
    };
    dataPool = {
      name = vars.zfsDataPool.name;
      mountPoint = vars.zfsDataPool.mountPoint;
      datasetMounts = map (dataset: "${vars.zfsDataPool.mountPoint}/${dataset}") vars.zfsDataPool.datasets;
    };
  });
  discoverStorageDevices = pkgs.writeShellScriptBin
    "discover-storage-devices-runtime"
    (builtins.readFile ../../../scripts/discover-storage-devices.sh);
  systemPackages =
    (with pkgs; [
      smartmontools
    ])
    ++ lib.optional vars.enableZfsDataPool config.boot.zfs.package;
  smartdPath =
    (with pkgs; [
      bash
      coreutils
      gawk
      jq
      smartmontools
      util-linux
    ])
    ++ lib.optional vars.enableZfsDataPool config.boot.zfs.package;
in
{
  environment.systemPackages = systemPackages;

  systemd.services.smartd = {
    description = "S.M.A.R.T. Daemon";
    wantedBy = [ "multi-user.target" ];
    after = [ "local-fs.target" ] ++ lib.optional vars.enableZfsDataPool "zfs.target";
    wants = lib.optional vars.enableZfsDataPool "zfs.target";
    path = smartdPath;
    preStart = ''
      install -d -m 0755 /run/storage-smartd
      tmp="$(mktemp /run/storage-smartd/smartd.conf.XXXXXX)"
      trap 'rm -f "$tmp"' EXIT
      {
        echo '# Autogenerated from evaluated storage inventory'
        echo 'DEFAULT -a'
        ${discoverStorageDevices}/bin/discover-storage-devices-runtime \
          --config-json-file ${discoveryConfig} \
          --format json \
          | jq -r '.allSmartDisks[] | .device + (if ((.smartctlArgs // []) | length) == 0 then "" else " " + (.smartctlArgs | join(" ")) end)'
      } >"$tmp"
      smartd --no-fork --quit=showtests --configfile="$tmp" >/dev/null
      chmod 0644 "$tmp"
      mv -f "$tmp" /run/storage-smartd/smartd.conf
      trap - EXIT
    '';
    serviceConfig = {
      Type = "notify";
      ExecStart = "${pkgs.smartmontools}/sbin/smartd --no-fork --configfile=/run/storage-smartd/smartd.conf";
      RuntimeDirectory = "storage-smartd";
      Restart = "on-failure";
      TimeoutStartSec = "2m";
      KillMode = "control-group";
    };
  };
}
