{ lib, pkgs, vars, ... }:

let
  inherit (vars) mainDisk dataDisks parityDisk;

  ## ─── MAIN SYSTEM DISK ────────────────────────────────────────
  systemDisk = {
    device = "/dev/disk/by-id/${mainDisk}";
    type   = "disk";
    content = {
      type = "gpt";
      partitions = {
        boot = {
          size = "512M";
          type = "EF00";
          content = {
            type = "filesystem";
            format = "vfat";
            mountpoint = "/boot";
          };
        };
        root = {
          size = "100%";
          content = {
            type = "btrfs";
            # Three subvolumes for impermanence-friendly layout
            subvolumes = {
              "@"       = { 
                mountpoint = "/";
                mountOptions = [ "compress=zstd" "noatime" ]; };
              "@nix"    = { 
                mountpoint = "/nix";     
                mountOptions = [ "compress=zstd" "noatime" ]; };
              "@persist"= { 
                mountpoint = "/persist"; 
                mountOptions = [ "compress=zstd" "noatime" ]; };
            };
          };
        };
      };
    };
  };

  ## ─── SNAPRAID DATA DISKS (XFS) ───────────────────────────────
  dataDiskDecls =
    lib.mkMerge (lib.imap0
      (idx: id:
        let ordinal = builtins.toString (idx + 1); in
        {
          disk = {
            "data${ordinal}" = {
              device = "/dev/disk/by-id/${id}";
              type   = "disk";
              content = {
                type = "gpt";
                partitions.data = {
                  size    = "100%";
                  content = {
                    type       = "filesystem";
                    format     = "xfs";
                    mountpoint = "/mnt/disk${ordinal}";
                  };
                };
              };
            };
          };
        })
      dataDisks);

  ## ─── PARITY DISK (XFS) ───────────────────────────────────────
  parityDiskDecl = {
    disk = {
      parity = {
        device = "/dev/disk/by-id/${parityDisk}";
        type   = "disk";
        content = {
          type = "gpt";
          partitions.parity = {
            size    = "100%";
            content = {
              type       = "filesystem";
              format     = "xfs";
              mountpoint = "/mnt/parity";
            };
          };
        };
      };
    };
  };

  ## ─── MergerFS SETUP ──────────────────────────────────────────
  mergerfsMountPoint = "/mnt/data";
  mergerfsSourceList =
    lib.concatStringsSep ":"
      (lib.imap0 (idx: _: "/mnt/disk${toString (idx + 1)}") dataDisks);
  mergerfsOptions = [
    "defaults"
    "allow_other"
    "use_ino"
    "minfreespace=10G"
    "category.create=epmfs"
  ];

  ## ─── SnapRAID CONFIG TEXT ───────────────────────────────────
  snapraidContentLines =
    builtins.concatStringsSep "\n"
      (lib.imap0 (idx: _: "content /mnt/disk${toString (idx + 1)}/.snapraid.content") dataDisks);
  snapraidDataLines =
    builtins.concatStringsSep "\n"
      (lib.imap0 (idx: _: "data d${toString (idx + 1)} /mnt/disk${toString (idx + 1)}") dataDisks);

  ## ─── SMARTD DEVICE LIST ─────────────────────────────────────
  smartDevices =
    [ "/dev/disk/by-id/${parityDisk}" ] ++
    map (id: "/dev/disk/by-id/${id}") dataDisks;

in
{
  ################################################################
  # Disko block
  ################################################################
  disko.devices = lib.mkMerge [
    { disk.system = systemDisk; }   # one attr-set for the system drive
    dataDiskDecls                   # merged attr-sets for data1,data2,…
    parityDiskDecl                  # attr-set for parity
  ];

  ################################################################
  # NixOS service/config block
  ################################################################
  environment.systemPackages = [ pkgs.snapraid pkgs.mergerfs pkgs.smartmontools ];

  # MergerFS pooled mount
  fileSystems.${mergerfsMountPoint} = {
    fsType  = "fuse.mergerfs";
    device  = mergerfsSourceList;
    options = mergerfsOptions;
  };

  # SnapRAID configuration file
  environment.etc."snapraid.conf".text = ''
    # ---- SnapRAID autogenerated by disko.nix ----
    parity /mnt/parity/snapraid.parity

    ${snapraidContentLines}

    ${snapraidDataLines}

    exclude *.unrecoverable
    exclude /tmp/
    exclude lost+found/
  '';

  # systemd timer: daily sync
  systemd.timers.snapraid-sync = {
    wantedBy = [ "timers.target" ];
    timerConfig = { OnCalendar = "daily"; Persistent = true; };
  };
  systemd.services.snapraid-sync = {
    script = "${pkgs.snapraid}/bin/snapraid sync";
    serviceConfig.Type = "oneshot";
  };

  # systemd timer: weekly scrub
  systemd.timers.snapraid-scrub = {
    wantedBy = [ "timers.target" ];
    timerConfig = { OnCalendar = "weekly"; Persistent = true; };
  };
  systemd.services.snapraid-scrub = {
    script = "${pkgs.snapraid}/bin/snapraid scrub -p 1 -o 10";
    serviceConfig.Type = "oneshot";
  };

  # SMART monitoring for all data + parity drives
  services.smartd = {
    enable = true;
    devices = map (dev: { device = dev; }) smartDevices;
  };
}
