{ vars, ... }:

{
  systemd.tmpfiles.rules = [
    "d ${vars.appdataRoot} 0755 root root -"
    "d ${vars.mediaRoot} 0755 root root -"
    "d ${vars.workspaceRoot} 0755 root root -"
    "d ${vars.usersWorkspaceRoot} 0755 root root -"
    "d ${vars.sharedWorkspaceRoot} 0755 root root -"
    "d ${vars.mediaDataRoot} 0755 root root -"
    "d ${vars.workspaceDataRoot} 0755 root root -"
    "d ${vars.usersWorkspaceDataRoot} 0755 root root -"
    "d ${vars.sharedWorkspaceDataRoot} 0755 root root -"

    "d ${vars.audiobookshelfDataDir} 0755 audiobookshelf audiobookshelf -"
    "d ${vars.audiobookshelfConfigDir} 0755 audiobookshelf audiobookshelf -"
    "d ${vars.audiobookshelfMetadataDir} 0755 audiobookshelf audiobookshelf -"
    "d ${vars.audiobookshelfBackupDir} 0755 audiobookshelf audiobookshelf -"
    "d ${vars.jellyfinDataDir} 0750 jellyfin jellyfin -"
    "d ${vars.jellyfinLogDir} 0750 jellyfin jellyfin -"
    "d ${vars.jellyseerrConfigDir} 0750 jellyseerr jellyseerr -"
    "d ${vars.jellyseerrConfigDir}/logs 0750 jellyseerr jellyseerr -"
    "d ${vars.kavitaDataDir} 0750 kavita kavita -"
    "d ${vars.paperlessDataDir} 0750 paperless paperless -"

    "d ${vars.immichManagedPhotosRoot} 0750 immich immich -"
    "d ${vars.immichManagedPhotosRoot}/backups 0750 immich immich -"
    "f ${vars.immichManagedPhotosRoot}/backups/.immich 0640 immich immich -"
    "d ${vars.immichManagedPhotosRoot}/encoded-video 0750 immich immich -"
    "f ${vars.immichManagedPhotosRoot}/encoded-video/.immich 0640 immich immich -"
    "d ${vars.immichManagedPhotosRoot}/library 0750 immich immich -"
    "f ${vars.immichManagedPhotosRoot}/library/.immich 0640 immich immich -"
    "d ${vars.immichManagedPhotosRoot}/profile 0750 immich immich -"
    "f ${vars.immichManagedPhotosRoot}/profile/.immich 0640 immich immich -"
    "d ${vars.immichManagedPhotosRoot}/thumbs 0750 immich immich -"
    "f ${vars.immichManagedPhotosRoot}/thumbs/.immich 0640 immich immich -"
    "d ${vars.immichManagedPhotosRoot}/upload 0750 immich immich -"
    "f ${vars.immichManagedPhotosRoot}/upload/.immich 0640 immich immich -"
    "d ${vars.immichExternalPhotosRoot} 2770 root immich -"
    "d ${vars.photosUploadDataRoot} 2770 root immich -"
    "d ${vars.paperlessConsumeDir} 2770 root paperless -"
    "d ${vars.documentsUploadDataRoot} 2770 root paperless -"
    "d ${vars.paperlessArchiveDir} 0750 paperless paperless -"
    "d ${vars.paperlessExportDir} 0770 paperless paperless -"
    "d ${vars.audiobooksRoot} 0755 root root -"
    "d ${vars.podcastsRoot} 0755 root root -"
    "d ${vars.ebooksRoot} 0755 root root -"
    "d ${vars.comicsRoot} 0755 root root -"
    "d ${vars.mangaRoot} 0755 root root -"
    "d ${vars.moviesRoot} 0755 root root -"
    "d ${vars.showsRoot} 0755 root root -"
    "d ${vars.homeVideosRoot} 0755 root root -"

    "d ${vars.sharedExchangeRoot} 2775 root users -"
    "d ${vars.sharedPublicRoot} 2775 root users -"
    "d ${vars.sharedExchangeDataRoot} 2775 root users -"
    "d ${vars.sharedPublicDataRoot} 2775 root users -"
  ];
}
